#    application.properties
#    spring.application.name=online-store
#    app-new-name=online-offer-store
#    stripe.apiUrl=https://stripe.api.com
#    stripe.enabled=true
#    stripe.timeout=1000
#    stripe.supported-currencies=USD,EUR,GBP

spring:
  application:
    name: shopping-cart
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart?createDatabaseIfNotExist=true
    username: root
    password: Sagar@123
  jpa:
    show-sql: true
  jwt:
    secret: jJtvuHNBJKr87WLP6R8c+JVaAd0vqsF+H0YMaBN1AzgZkl1O0ihIJ4ys8T5DCBvrpFkvv7CdVnkwEm1/VhdRBQ==
    accessTokenExpiration: 300 # 5m
    refreshTokenExpiration: 604800 # 7d



